### Get all bars from the database
GET {{url}}/bars

### Find bar by id

GET {{url}}/bars/7
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### Find bars by title
GET {{url}}/bars/title/the
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### Find bars by genre
GET {{url}}/bars/genre/humor
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### Create a Bar

POST {{url}}/bars
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "title": "",
  "content": "",
  "date": "0000-00-00",
  "genre": "",
  "authorName": "",
  "authorDescription": ""
}

### Delete a bar
DELETE {{url}}/bars/5
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

### Reset token
GET {{url}}/auth/test/

> {%
    client.global.set("jwt_token", null);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

