### Get all bars from the database
GET {{url}}/bars

### Find bar by id

GET {{url}}/bars/6

### Create a Bar

POST {{url}}/bars
Content-Type: application/json

{
  "title": "",
  "content": "",
  "date": "0000-00-00",
  "genre": "",
  "authorName": "",
  "authorDescription": ""
}

### Delete a bar
DELETE {{url}}/bars/5


